### ISSUE TITLE
Código terminado y funcionando

### ISSUE THREAD

**Issue by sandra86code** [sandra86code/ProyectoBiblioteca#1]
Buenas tardes, Inma:

Conseguí resolver el problema que me estaba dando el programa, así que ya está acabada la parte del código y también he añadido el UML final.
Por si le puedes echar un vistazo, antes de que nos metamos en añadir lo de las bases de datos.

Gracias.

**Comment by ioliasa** [comment]
Hola Sandra, en principio lo veo bien, mucho más de lo que pido, por lo que cuando le añadamos la base de datos puedes hacer sólo la parte añadir autor, libro y ejemplar.
